/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as DiscoverRouteImport } from './routes/discover'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as RefundPolicyRouteImport } from './routes/refund-policy'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SuccessRouteImport } from './routes/success'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AuthenticatedDashboardRouteRouteImport } from './routes/_authenticated/dashboard/route'
import { Route as PSlugRouteImport } from './routes/p.$slug'
import { Route as UHandleRouteImport } from './routes/u.$handle'
import { Route as AuthenticatedDashboardIndexRouteImport } from './routes/_authenticated/dashboard/index'
import { Route as AuthenticatedDashboardAnalyticsRouteImport } from './routes/_authenticated/dashboard/analytics'
import { Route as AuthenticatedDashboardDiscountsRouteImport } from './routes/_authenticated/dashboard/discounts'
import { Route as AuthenticatedDashboardReferralsRouteImport } from './routes/_authenticated/dashboard/referrals'
import { Route as AuthenticatedDashboardSettingsRouteImport } from './routes/_authenticated/dashboard/settings'
import { Route as ImgAvatarUserIdRouteImport } from './routes/img.avatar.$userId'
import { Route as ImgProductProductIdRouteImport } from './routes/img.product.$productId'
import { Route as AuthenticatedDashboardStripeRefreshRouteImport } from './routes/_authenticated/dashboard/stripe.refresh'
import { Route as AuthenticatedDashboardStripeReturnRouteImport } from './routes/_authenticated/dashboard/stripe.return'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverRoute = DiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundPolicyRoute = RefundPolicyRouteImport.update({
  id: '/refund-policy',
  path: '/refund-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SuccessRoute = SuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRouteRoute =
  AuthenticatedDashboardRouteRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const PSlugRoute = PSlugRouteImport.update({
  id: '/p/$slug',
  path: '/p/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const UHandleRoute = UHandleRouteImport.update({
  id: '/u/$handle',
  path: '/u/$handle',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDashboardRouteRoute,
  } as any)
const AuthenticatedDashboardAnalyticsRoute =
  AuthenticatedDashboardAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AuthenticatedDashboardRouteRoute,
  } as any)
const AuthenticatedDashboardDiscountsRoute =
  AuthenticatedDashboardDiscountsRouteImport.update({
    id: '/discounts',
    path: '/discounts',
    getParentRoute: () => AuthenticatedDashboardRouteRoute,
  } as any)
const AuthenticatedDashboardReferralsRoute =
  AuthenticatedDashboardReferralsRouteImport.update({
    id: '/referrals',
    path: '/referrals',
    getParentRoute: () => AuthenticatedDashboardRouteRoute,
  } as any)
const AuthenticatedDashboardSettingsRoute =
  AuthenticatedDashboardSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedDashboardRouteRoute,
  } as any)
const ImgAvatarUserIdRoute = ImgAvatarUserIdRouteImport.update({
  id: '/img/avatar/$userId',
  path: '/img/avatar/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const ImgProductProductIdRoute = ImgProductProductIdRouteImport.update({
  id: '/img/product/$productId',
  path: '/img/product/$productId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardStripeRefreshRoute =
  AuthenticatedDashboardStripeRefreshRouteImport.update({
    id: '/stripe/refresh',
    path: '/stripe/refresh',
    getParentRoute: () => AuthenticatedDashboardRouteRoute,
  } as any)
const AuthenticatedDashboardStripeReturnRoute =
  AuthenticatedDashboardStripeReturnRouteImport.update({
    id: '/stripe/return',
    path: '/stripe/return',
    getParentRoute: () => AuthenticatedDashboardRouteRoute,
  } as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/discover': typeof DiscoverRoute
  '/faq': typeof FaqRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/success': typeof SuccessRoute
  '/terms': typeof TermsRoute
  '/dashboard': typeof AuthenticatedDashboardRouteRouteWithChildren
  '/p/$slug': typeof PSlugRoute
  '/u/$handle': typeof UHandleRoute
  '/dashboard/analytics': typeof AuthenticatedDashboardAnalyticsRoute
  '/dashboard/discounts': typeof AuthenticatedDashboardDiscountsRoute
  '/dashboard/referrals': typeof AuthenticatedDashboardReferralsRoute
  '/dashboard/settings': typeof AuthenticatedDashboardSettingsRoute
  '/img/avatar/$userId': typeof ImgAvatarUserIdRoute
  '/img/product/$productId': typeof ImgProductProductIdRoute
  '/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/dashboard/stripe/refresh': typeof AuthenticatedDashboardStripeRefreshRoute
  '/dashboard/stripe/return': typeof AuthenticatedDashboardStripeReturnRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/discover': typeof DiscoverRoute
  '/faq': typeof FaqRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/success': typeof SuccessRoute
  '/terms': typeof TermsRoute
  '/p/$slug': typeof PSlugRoute
  '/u/$handle': typeof UHandleRoute
  '/dashboard/analytics': typeof AuthenticatedDashboardAnalyticsRoute
  '/dashboard/discounts': typeof AuthenticatedDashboardDiscountsRoute
  '/dashboard/referrals': typeof AuthenticatedDashboardReferralsRoute
  '/dashboard/settings': typeof AuthenticatedDashboardSettingsRoute
  '/img/avatar/$userId': typeof ImgAvatarUserIdRoute
  '/img/product/$productId': typeof ImgProductProductIdRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
  '/dashboard/stripe/refresh': typeof AuthenticatedDashboardStripeRefreshRoute
  '/dashboard/stripe/return': typeof AuthenticatedDashboardStripeReturnRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/discover': typeof DiscoverRoute
  '/faq': typeof FaqRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/success': typeof SuccessRoute
  '/terms': typeof TermsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRouteRouteWithChildren
  '/p/$slug': typeof PSlugRoute
  '/u/$handle': typeof UHandleRoute
  '/_authenticated/dashboard/analytics': typeof AuthenticatedDashboardAnalyticsRoute
  '/_authenticated/dashboard/discounts': typeof AuthenticatedDashboardDiscountsRoute
  '/_authenticated/dashboard/referrals': typeof AuthenticatedDashboardReferralsRoute
  '/_authenticated/dashboard/settings': typeof AuthenticatedDashboardSettingsRoute
  '/img/avatar/$userId': typeof ImgAvatarUserIdRoute
  '/img/product/$productId': typeof ImgProductProductIdRoute
  '/_authenticated/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/_authenticated/dashboard/stripe/refresh': typeof AuthenticatedDashboardStripeRefreshRoute
  '/_authenticated/dashboard/stripe/return': typeof AuthenticatedDashboardStripeReturnRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/discover'
    | '/faq'
    | '/login'
    | '/pricing'
    | '/privacy'
    | '/refund-policy'
    | '/sitemap.xml'
    | '/success'
    | '/terms'
    | '/dashboard'
    | '/p/$slug'
    | '/u/$handle'
    | '/dashboard/analytics'
    | '/dashboard/discounts'
    | '/dashboard/referrals'
    | '/dashboard/settings'
    | '/img/avatar/$userId'
    | '/img/product/$productId'
    | '/dashboard/'
    | '/dashboard/stripe/refresh'
    | '/dashboard/stripe/return'
    | '/api/public/payments/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/discover'
    | '/faq'
    | '/login'
    | '/pricing'
    | '/privacy'
    | '/refund-policy'
    | '/sitemap.xml'
    | '/success'
    | '/terms'
    | '/p/$slug'
    | '/u/$handle'
    | '/dashboard/analytics'
    | '/dashboard/discounts'
    | '/dashboard/referrals'
    | '/dashboard/settings'
    | '/img/avatar/$userId'
    | '/img/product/$productId'
    | '/dashboard'
    | '/dashboard/stripe/refresh'
    | '/dashboard/stripe/return'
    | '/api/public/payments/webhook'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/discover'
    | '/faq'
    | '/login'
    | '/pricing'
    | '/privacy'
    | '/refund-policy'
    | '/sitemap.xml'
    | '/success'
    | '/terms'
    | '/_authenticated/dashboard'
    | '/p/$slug'
    | '/u/$handle'
    | '/_authenticated/dashboard/analytics'
    | '/_authenticated/dashboard/discounts'
    | '/_authenticated/dashboard/referrals'
    | '/_authenticated/dashboard/settings'
    | '/img/avatar/$userId'
    | '/img/product/$productId'
    | '/_authenticated/dashboard/'
    | '/_authenticated/dashboard/stripe/refresh'
    | '/_authenticated/dashboard/stripe/return'
    | '/api/public/payments/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  DiscoverRoute: typeof DiscoverRoute
  FaqRoute: typeof FaqRoute
  LoginRoute: typeof LoginRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  RefundPolicyRoute: typeof RefundPolicyRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SuccessRoute: typeof SuccessRoute
  TermsRoute: typeof TermsRoute
  PSlugRoute: typeof PSlugRoute
  UHandleRoute: typeof UHandleRoute
  ImgAvatarUserIdRoute: typeof ImgAvatarUserIdRoute
  ImgProductProductIdRoute: typeof ImgProductProductIdRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover': {
      id: '/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof DiscoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund-policy': {
      id: '/refund-policy'
      path: '/refund-policy'
      fullPath: '/refund-policy'
      preLoaderRoute: typeof RefundPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/success': {
      id: '/success'
      path: '/success'
      fullPath: '/success'
      preLoaderRoute: typeof SuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/p/$slug': {
      id: '/p/$slug'
      path: '/p/$slug'
      fullPath: '/p/$slug'
      preLoaderRoute: typeof PSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/$handle': {
      id: '/u/$handle'
      path: '/u/$handle'
      fullPath: '/u/$handle'
      preLoaderRoute: typeof UHandleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthenticatedDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRouteRoute
    }
    '/_authenticated/dashboard/analytics': {
      id: '/_authenticated/dashboard/analytics'
      path: '/analytics'
      fullPath: '/dashboard/analytics'
      preLoaderRoute: typeof AuthenticatedDashboardAnalyticsRouteImport
      parentRoute: typeof AuthenticatedDashboardRouteRoute
    }
    '/_authenticated/dashboard/discounts': {
      id: '/_authenticated/dashboard/discounts'
      path: '/discounts'
      fullPath: '/dashboard/discounts'
      preLoaderRoute: typeof AuthenticatedDashboardDiscountsRouteImport
      parentRoute: typeof AuthenticatedDashboardRouteRoute
    }
    '/_authenticated/dashboard/referrals': {
      id: '/_authenticated/dashboard/referrals'
      path: '/referrals'
      fullPath: '/dashboard/referrals'
      preLoaderRoute: typeof AuthenticatedDashboardReferralsRouteImport
      parentRoute: typeof AuthenticatedDashboardRouteRoute
    }
    '/_authenticated/dashboard/settings': {
      id: '/_authenticated/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof AuthenticatedDashboardSettingsRouteImport
      parentRoute: typeof AuthenticatedDashboardRouteRoute
    }
    '/img/avatar/$userId': {
      id: '/img/avatar/$userId'
      path: '/img/avatar/$userId'
      fullPath: '/img/avatar/$userId'
      preLoaderRoute: typeof ImgAvatarUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/img/product/$productId': {
      id: '/img/product/$productId'
      path: '/img/product/$productId'
      fullPath: '/img/product/$productId'
      preLoaderRoute: typeof ImgProductProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard/stripe/refresh': {
      id: '/_authenticated/dashboard/stripe/refresh'
      path: '/stripe/refresh'
      fullPath: '/dashboard/stripe/refresh'
      preLoaderRoute: typeof AuthenticatedDashboardStripeRefreshRouteImport
      parentRoute: typeof AuthenticatedDashboardRouteRoute
    }
    '/_authenticated/dashboard/stripe/return': {
      id: '/_authenticated/dashboard/stripe/return'
      path: '/stripe/return'
      fullPath: '/dashboard/stripe/return'
      preLoaderRoute: typeof AuthenticatedDashboardStripeReturnRouteImport
      parentRoute: typeof AuthenticatedDashboardRouteRoute
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedDashboardRouteRouteChildren {
  AuthenticatedDashboardAnalyticsRoute: typeof AuthenticatedDashboardAnalyticsRoute
  AuthenticatedDashboardDiscountsRoute: typeof AuthenticatedDashboardDiscountsRoute
  AuthenticatedDashboardReferralsRoute: typeof AuthenticatedDashboardReferralsRoute
  AuthenticatedDashboardSettingsRoute: typeof AuthenticatedDashboardSettingsRoute
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
  AuthenticatedDashboardStripeRefreshRoute: typeof AuthenticatedDashboardStripeRefreshRoute
  AuthenticatedDashboardStripeReturnRoute: typeof AuthenticatedDashboardStripeReturnRoute
}

const AuthenticatedDashboardRouteRouteChildren: AuthenticatedDashboardRouteRouteChildren =
  {
    AuthenticatedDashboardAnalyticsRoute: AuthenticatedDashboardAnalyticsRoute,
    AuthenticatedDashboardDiscountsRoute: AuthenticatedDashboardDiscountsRoute,
    AuthenticatedDashboardReferralsRoute: AuthenticatedDashboardReferralsRoute,
    AuthenticatedDashboardSettingsRoute: AuthenticatedDashboardSettingsRoute,
    AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
    AuthenticatedDashboardStripeRefreshRoute:
      AuthenticatedDashboardStripeRefreshRoute,
    AuthenticatedDashboardStripeReturnRoute:
      AuthenticatedDashboardStripeReturnRoute,
  }

const AuthenticatedDashboardRouteRouteWithChildren =
  AuthenticatedDashboardRouteRoute._addFileChildren(
    AuthenticatedDashboardRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRouteRoute: typeof AuthenticatedDashboardRouteRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRouteRoute:
    AuthenticatedDashboardRouteRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  DiscoverRoute: DiscoverRoute,
  FaqRoute: FaqRoute,
  LoginRoute: LoginRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  RefundPolicyRoute: RefundPolicyRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SuccessRoute: SuccessRoute,
  TermsRoute: TermsRoute,
  PSlugRoute: PSlugRoute,
  UHandleRoute: UHandleRoute,
  ImgAvatarUserIdRoute: ImgAvatarUserIdRoute,
  ImgProductProductIdRoute: ImgProductProductIdRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
